### ISSUE TITLE
La commande de backup inc retourne une erreur si pas de full

### ISSUE THREAD

**Issue by ebreton** [epfl-idevelop/jahia2wp#147]
Ce comportement bloque l'execution des cronjobs. L'idéal serait que la commande lance un script de backup full si il n'en existe pas. Ce qui évitera d'attendre le cronjob quotidien de backup full

```
ERROR:root:http://lpbs-next.epfl.ch/ - WP backup failed: WP tar lpbs-next_20171208065651_full9_inc10.tar could not be created
Traceback (most recent call last):
  File "src/jahia2wp.py", line 241, in <module>
    dispatch(__doc__)
  File "/srv/subdomains/venv/lib/python3.5/site-packages/docopt_dispatch.py", line 34, in __call__
    function(**self._kwargify(arguments))
  File "src/jahia2wp.py", line 187, in backup_many
    backup_type=backup_type
  File "/srv/subdomains/jahia2wp/src/wordpress/backup.py", line 226, in backup
    base_name += "".join((self.max_full_number, "_inc", self.next_inc_number))
  File "/srv/subdomains/jahia2wp/src/wordpress/backup.py", line 124, in next_inc_number
    raise WPException("Incremental backup is based on full backup. But there is no full backup")
wordpress.models.WPException: Incremental backup is based on full backup. But there is no full backup
```

**Comment by ebreton** [comment]
Corrigé dans PR #154 . La commande de backup crée un backup full ou un incremental en fonction de ce qu'il y a déjà pour la journée
