### ISSUE TITLE
Exception dans la commande backup si un site de la source de vérité n'a pas été généré

### ISSUE THREAD

**Issue by ebreton** [epfl-idevelop/jahia2wp#163]
Exemple pour cette source de vérité:

```
wp_site_url,wp_default_site_title,site_type,openshift_env,category,theme,theme_faculty,status,installs_locked,updates_automatic,langs,unit_name,comment
...
https://c4dt.epfl.ch,Center for Digital,wordpress,subdomains,GeneralPublic,epfl-master,,yes,yes,yes,en,LCA1,"site de centre ,en cours de création"
```

```
$ python jahia2wp.py backup-many /srv/data.csv
WARNING:root:The optional environment variable BACKUP_PATH is not set, using '/srv/subdomains/jahia2wp/data/backups' as default
INFO:root:The CSV file is validated !
...
9 websites will now be backuped...
...
INFO:root:http://c4dt.epfl.ch/ - Backuping into /srv/subdomains/jahia2wp/data/backups/c4dt
Traceback (most recent call last):
  File "jahia2wp.py", line 264, in <module>
    dispatch(__doc__)
  File "/srv/subdomains/venv/lib/python3.5/site-packages/docopt_dispatch.py", line 34, in __call__
    function(**self._kwargify(arguments))
  File "jahia2wp.py", line 187, in backup_many
    row["wp_site_url"]
  File "/srv/subdomains/jahia2wp/src/wordpress/backup.py", line 143, in backup
    self.generate_wp_files()
  File "/srv/subdomains/jahia2wp/src/wordpress/backup.py", line 113, in generate_wp_files
    if not os.listdir(self.wp_site.path):
FileNotFoundError: [Errno 2] No such file or directory: '/srv/subdomains/c4dt.epfl.ch/htdocs'
```

Il suffit pour corriger de remplacer `if not os.listdir(self.wp_site.path)`: par `if not os.path.exists(self.wp_site.path)`. 

Je prends.

**Comment by ebreton** [comment]
zut, j'ai pushé direct dans master. désolé...

**Comment by LuluTchab** [comment]
Pas grave, tu paies le café vendredi (quand tout le monde sera de retour) et on t'en voudra pas ;-)
