### ISSUE TITLE
encoding title

### ISSUE THREAD

**Issue by jaepetto** [epfl-idevelop/jahia2wp#165]
INFO:root:https://vpsi-next.epfl.ch/ - Downloading WP...
Traceback (most recent call last):
  File "jahia2wp.py", line 264, in <module>
    dispatch(__doc__)
  File "/srv/subdomains/venv/lib/python3.5/site-packages/docopt_dispatch.py", line 34, in __call__
    function(**self._kwargify(arguments))
  File "jahia2wp.py", line 172, in generate_many
    theme_faculty=row["theme_faculty"],
  File "/srv/subdomains/jahia2wp/src/wordpress/generator.py", line 153, in generate
    if not self.install_wp():
  File "/srv/subdomains/jahia2wp/src/wordpress/generator.py", line 233, in install_wp
    if not self.run_wp_cli(command.format(self.wp_site, self.wp_admin)):
  File "/srv/subdomains/jahia2wp/src/wordpress/generator.py", line 107, in run_wp_cli
    return self.wp_config.run_wp_cli(command)
  File "/srv/subdomains/jahia2wp/src/wordpress/config.py", line 104, in run_wp_cli
    return Utils.run_command(cmd)
  File "/srv/subdomains/jahia2wp/src/utils.py", line 48, in run_command
    command_bytes = command.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 75: ordinal not in range(128)

**Comment by LuluTchab** [comment]
Le paramètre `encoding` existe pour `Utils.run_command` mais il n'a pas été ajouté dans toute la chaine d'appel en amont... 
`WPGenerator.run_wp_cli` -> `WPConfig.run_wp_cli` -> `Utils.run_command` ...

Un peu de doc pourrait être pas mal aussi pour savoir comment définir ce paramètre "encoding"... est-ce que ça doit être l'encodage dans laquelle la commande est passée ? pas très clair... et pas de commentaire non plus à la fonction... dommage.

**Comment by LuluTchab** [comment]
Corrigé dans la PR https://github.com/epfl-idevelop/jahia2wp/pull/193
