### ISSUE TITLE
Problème de chemin avec la configuration des plugins

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/jahia2wp#88]
En suivant la doc, j'essaie de créer un nouveau site mais j'obtiens :

```bash
(venv) www-data@ff51864a04b4:/srv/your-env/jahia2wp/src$ python jahia2wp.py generate 'your-env' http://localhost --wp-title="Unicorn" --admin-password=unicorn
INFO - your-env - generate - http://localhost/ - Setting up DB...
INFO - your-env - generate - http://localhost/ - Downloading WP...
INFO - your-env - generate - http://localhost/ - Activating theme...
INFO - your-env - generate - http://localhost/ - Installing plugins...
INFO - your-env - generate_plugins - WPGenerator.generate_plugins(): Add parameter for 'batch file' (YAML)
ERROR - your-env - __init__ - WPPluginList - Generic config path not exists: src/wordpress/tests/plugins/generic
ERROR - your-env - __init__ - WPPluginList - Generic plugin list not exists: src/wordpress/tests/plugins/generic/config-lot1.yml
ERROR - your-env - __init__ - WPPluginList - Specific config path not exists: src/wordpress/tests/plugins/specific
Traceback (most recent call last):
  File "jahia2wp.py", line 241, in <module>
    dispatch(__doc__)
  File "/srv/your-env/venv/lib/python3.5/site-packages/docopt_dispatch.py", line 34, in __call__
    function(**self._kwargify(arguments))
  File "jahia2wp.py", line 122, in generate
    if not wp_generator.generate():
  File "/srv/your-env/jahia2wp/src/wordpress/generator.py", line 176, in generate
    self.generate_plugins()
  File "/srv/your-env/jahia2wp/src/wordpress/generator.py", line 106, in generate_plugins
    plugin_list = WPPluginList(PLUGINS_CONFIG_GENERIC_FOLDER, 'config-lot1.yml', PLUGINS_CONFIG_SPECIFIC_FOLDER)
  File "/srv/your-env/jahia2wp/src/wordpress/plugins/models.py", line 67, in __init__
    plugin_list = yaml.load(open(generic_plugin_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'src/wordpress/tests/plugins/generic/config-lot1.yml'
```

Je peux contourner le problème en changeant le répertoire courant :

```bash
(venv) www-data@2b9ed90ca993:/srv/your-env/jahia2wp$ python src/jahia2wp.py generate 'your-env' http://localhost --wp-title="Unicorn" --admin-password=unicorn
INFO - your-env - generate - http://localhost/ - Setting up DB...
INFO - your-env - generate - http://localhost/ - Downloading WP...
INFO - your-env - generate - http://localhost/ - Activating theme...
INFO - your-env - generate - http://localhost/ - Installing plugins...
INFO - your-env - generate_plugins - WPGenerator.generate_plugins(): Add parameter for 'batch file' (YAML)
INFO - your-env - generate_plugins - http://localhost/ - Plugins - hello: Uninstalling...
INFO - your-env - generate_plugins - http://localhost/ - Plugins - hello: Not installed!
INFO - your-env - generate_plugins - http://localhost/ - Plugins - add-to-any: Installing...
INFO - your-env - generate_plugins - http://localhost/ - Plugins - add-to-any: Installed!
INFO - your-env - generate_plugins - http://localhost/ - Plugins - add-to-any: Setting state...
INFO - your-env - generate_plugins - http://localhost/ - Plugins - add-to-any: Activated!
INFO - your-env - generate_plugins - http://localhost/ - Plugins - akismet: Setting state...
INFO - your-env - generate_plugins - http://localhost/ - Plugins - akismet: Deactivated!
INFO - your-env - generate - http://localhost/ - Creating webmaster accounts...
Successfully created new WordPress site at http://localhost/
```

mais ce serait bien que ce soit indépendant.

**Comment by LuluTchab** [comment]
Hello,

1. Est-ce que tu es sûr d'avoir la dernière version du code ? (on a fait des modifs cet après-midi à propos de ce problème)
1. Il semblerait que tu aies la variable `PLUGINS_CONFIG_BASE_PATH` qui soit initialisée dans ton environnement et elle doit l'être avec `src/wordpress/tests/plugins/`. Il faut virer cette variable d'environnement (si je ne me trompe pas, elle a été ajoutée dans le `.env` puis retirée rapidement après)

**Comment by williambelle** [comment]
1. Oui, j'ai la dernière version.
2. Oui, j'ai la variable `PLUGINS_CONFIG_BASE_PATH`

Je vois toujours la variable ici : https://github.com/epfl-idevelop/jahia2wp/blob/e801af70726110973558ab2a1e751209e79223cc/.env.sample#L26

**Comment by LuluTchab** [comment]
Je t'ai dit une bêtise avant (enfin, partiellement XD).

Si la variable `PLUGINS_CONFIG_BASE_PATH` n'est pas dans le `.env` ça va fonctionner nickel car elle sera initialisée à la bonne valeur dans le code.
Si la variable existe dans `.env`, il faut changer la valeur par défaut de celle-ci pour mettre : 
`PLUGINS_CONFIG_BASE_PATH=data/plugins/`
En effet, la valeur du `.env.sample` doit être modifiée, elle n'est utilisée tel quel que par Travis pour les tests.

Vais check si la doc est à jour à propos de ça.

**Comment by ebreton** [comment]
@williambelle , est ce que tu as checké ton `.env` ? le bug est toujours là ?

**Comment by williambelle** [comment]
C'est tout bon.

Merci !
